client_columns = ['id', 'first_name', 'last_name', 'image_url', 'username', 'password', 'email_address']
client_signup_columns = ['id', 'username']
restaurant_columns = ['id', 'name', 'email_address', 'address', 'phone_number', 'bio','city', 'profile_url', 'banner_url', 'password']
token_columns = ['client_id', 'token']
restuarant_signup_columns = ['id', 'name', 'email_address']
restaurants_columns = ['id', 'name', 'email_address', 'address', 'phone_number', 'bio','city', 'profile_url', 'banner_url']
menu_columns = ['id','name', 'description','image_url', 'price', 'restaurant_id']
