patient_columns = ['id', 'first_name', 'last_name', 'date_of_birth', 'phone_number', 'contact_address','health_card_number','email_address', 'password','gender', 'emergency_contact']
patient_signup_columns = ['id', 'email_address', 'health_card_number']
doctor_columns = ['id', 'first_name', 'last_name', 'medical_id', 'speciality', 'email_address','password','image_url']
token_columns = ['patient_id', 'token']
doctor_token_columns = ['doctor_id', 'token']
doctor_signup_columns = ['id', 'first_name', 'last_name', 'medical_id', 'speciality', 'email_address', 'password', 'image_url']
doctors_columns = ['id', 'first_name', 'last_name', 'medical_id', 'speciality', 'email_address', 'password', 'image_url']
